services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: campify
      POSTGRES_PASSWORD: campify
      POSTGRES_DB: campify
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mosquitto:
    image: eclipse-mosquitto:2
    ports:
      - '1883:1883'
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf

volumes:
  postgres-data:
